# -*- coding: utf-8 -*-
"""Ticket Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_g_OyPx_eIvll2H_3OuXgY6v307PdLVp
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import accuracy_score

tickets = pd.read_csv("servicenow_ticket.csv");

print(f"Number of rows and columns: {tickets.shape}");
print(f"Columns names: {tickets.columns}");

## EDA and data preprocessing
tickets.head()
tickets.isnull().sum()

print(f"Unique Issues : {len(tickets['Short description'].unique())}\n");
group =tickets.groupby('Assignment group');

print(f"Below are the number of tickets assigned to each assignment group \n\n{group['Short description'].count()}");

vector = TfidfVectorizer();
le = LabelEncoder();

issue = tickets['Short description'] + " " + tickets['Description'];

X = vector.fit_transform(issue);
y = le.fit_transform(tickets['Assignment group']);

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42);

model = LogisticRegression(max_iter=100);

model.fit(X_train, y_train);

y_pred = model.predict(X_test);

accuracy = accuracy_score(y_test, y_pred);
print(f"Model Accuracy : {accuracy}");

short_description = "permission";
description = "issue";

new_ticket = short_description + " " + description;

input = vector.transform([new_ticket]);
result_label = model.predict(input);

predicted_assignment_group = le.inverse_transform(result_label);

print(f"Predicted Assignment group : {predicted_assignment_group[0]}");

